### PR TITLE
Resolved some issues, presumably from newer GitLab versions

### PR DESCRIPTION
**Pull request by attie**

### CODE REVIEW

**Comment by pdeffendol** [comment]
Thanks!  I haven't used Redmine, and therefore this plugin, for a while now.  Are you aware of a minimum version or GitLab and/or Redmine that this requires now?

**Comment by attie** [comment]
No problem!

I'm afraid I'm not aware of the minimum version(s)... but I'm currently running:
- Redmine `4.0.2`
- GitLab `12.1.4 (34d086f3e14)`

The major difference appears to be GitLab's scope requirements... I'll have a quick look to see if it's obvious when they were introduced.

**Comment by attie** [comment]
I've had a quick look [here](https://about.gitlab.com/releases/), and nothing stands out at me...

**Comment by pdeffendol** [comment]
Great, I'll merge it in.  Thanks for contributing!

**Pull request merged**
